services:
  cms:
    image: nginx
    volumes:
      - ./cms/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cms/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cms/html:/data/www:ro
    ports:
    - "8000:80"
    networks:
      demo-network:
        aliases:
          - cms
  place-app-vue-ssr:
    image: node:current-alpine
    working_dir: /build
    volumes:
      - ../:/build
    command: ["node", "./src/server.js"]
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      demo-network:
        aliases:
          - place-app-vue-ssr

volumes:
  node_modules:

networks:
  demo-network: